### ISSUE TITLE
Using editable-text with CFS filerecord meta information

### ISSUE THREAD

**Issue by todda00** [JackAdams/meteor-editable-text#3]
I am using CFS (https://github.com/CollectionFS/Meteor-CollectionFS) for file storage and want to use editable-text to edit the embedded document within the collection. Seems like the package is not targeted at this use case, but doesn't seem like it would be too difficult to modify. This is my template call I am using to show / edit the file's title which is stored in meta.title

```
<h1>{{> editableText collection='cfs.media.filerecord' field='meta.title'}}</h1>
```

It shows the item properly, but is failing a Method check():

```
Exception while invoking method '_editableTextWrite' Error: Match error: Expected plain object
I20150119-15:31:36.362(-5)?     at checkSubtree (packages/check/match.js:279:1)
I20150119-15:31:36.363(-5)?     at check (packages/check/match.js:32:1)
I20150119-15:31:36.363(-5)?     at [object Object].Meteor.methods._editableTextWrite (packages/babrahams:editable-text/lib/editable_text_common.js:154:1)
```

**Comment by todda00** [comment]
I created a pull-request with a simple change to allow the method to work with CollectionFS - https://github.com/JackAdams/meteor-editable-text/pull/4
